version: '3.7'

services:
  environment:
    image: recruitment-image
    container_name: test
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true